### PR TITLE
Disqus

### PR DESCRIPTION
**Pull request by andrewalker**
See #22. Just opened a new one so that I could rebase and not lose history.

### CODE REVIEW

**Comment by andrewalker** [comment]
Still missing a couple of things. I'll finish later.

**Comment by andrewalker** [comment]
So, copying the comment by @xsawyerx on #22, these were the missing steps for this to be merged:
- [x] Convert to `Moo`
- [x] Move all endpoints for the `Builtin` system to `Builtin.pm`
- [x] Remove the `_tt` and `.tt` from attribute names and template filenames respectively.
- [x] Convert `Class::Load` to `Module::Runtime`.
- [x] Have `Builtin.pm` load `Builtin::Endpoints`.
- [x] `new_captcha_code()` call will break because the Captcha isn't loaded.
- [x] Template attributes should have `_template` postfix to be template agnostic.
- [x] Rebase from `master` once #20 is merged.

As you can see, the only thing missing is _Remove the `_tt` and `.tt` from attribute names and template filenames respectively_. The problem is that whenever I remove the .tt extension, it cannot find the templates. You can try to investigate, I'm kind of stuck. I think it's better to merge it this way, it can be fixed later on.

**Comment by andrewalker** [comment]
Rebased once again after #28.

**Comment by xsawyerx** [comment]
Merged! All issues were addressed.

@andrewalker++ `for $inf`.

**Pull request closed without merging**
